# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ddtkh\Desktop\qc_scale\com_config_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ComConfig(object):
    def setupUi(self, ComConfig):
        ComConfig.setObjectName("ComConfig")
        ComConfig.resize(432, 220)
        self.groupBox = QtWidgets.QGroupBox(ComConfig)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 411, 111))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 51, 16))
        self.label_3.setObjectName("label_3")
        self.leStopBit = QtWidgets.QLineEdit(self.groupBox)
        self.leStopBit.setGeometry(QtCore.QRect(330, 50, 71, 20))
        self.leStopBit.setObjectName("leStopBit")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(160, 50, 51, 16))
        self.label_6.setObjectName("label_6")
        self.leByteSize = QtWidgets.QLineEdit(self.groupBox)
        self.leByteSize.setGeometry(QtCore.QRect(210, 50, 61, 20))
        self.leByteSize.setObjectName("leByteSize")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.label_2.setObjectName("label_2")
        self.dbParity = QtWidgets.QComboBox(self.groupBox)
        self.dbParity.setGeometry(QtCore.QRect(210, 80, 61, 22))
        self.dbParity.setAcceptDrops(False)
        self.dbParity.setEditable(False)
        self.dbParity.setObjectName("dbParity")
        self.dbParity.addItem("")
        self.dbParity.addItem("")
        self.dbParity.addItem("")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(160, 80, 41, 16))
        self.label_4.setObjectName("label_4")
        self.lePortNum = QtWidgets.QLineEdit(self.groupBox)
        self.lePortNum.setGeometry(QtCore.QRect(80, 50, 71, 20))
        self.lePortNum.setObjectName("lePortNum")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(280, 50, 41, 16))
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label.setObjectName("label")
        self.leBaurdrate = QtWidgets.QLineEdit(self.groupBox)
        self.leBaurdrate.setGeometry(QtCore.QRect(80, 80, 71, 20))
        self.leBaurdrate.setObjectName("leBaurdrate")
        self.butAddNew = QtWidgets.QPushButton(self.groupBox)
        self.butAddNew.setGeometry(QtCore.QRect(280, 80, 121, 23))
        self.butAddNew.setObjectName("butAddNew")
        self.leConfigName = QtWidgets.QLineEdit(self.groupBox)
        self.leConfigName.setGeometry(QtCore.QRect(80, 20, 321, 20))
        self.leConfigName.setObjectName("leConfigName")
        self.groupBox_2 = QtWidgets.QGroupBox(ComConfig)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 130, 411, 81))
        self.groupBox_2.setObjectName("groupBox_2")
        self.dbConfigName = QtWidgets.QComboBox(self.groupBox_2)
        self.dbConfigName.setGeometry(QtCore.QRect(90, 20, 311, 22))
        self.dbConfigName.setAcceptDrops(False)
        self.dbConfigName.setEditable(False)
        self.dbConfigName.setObjectName("dbConfigName")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.label_7.setObjectName("label_7")
        self.butDelete = QtWidgets.QPushButton(self.groupBox_2)
        self.butDelete.setGeometry(QtCore.QRect(280, 50, 121, 23))
        self.butDelete.setObjectName("butDelete")

        self.retranslateUi(ComConfig)
        QtCore.QMetaObject.connectSlotsByName(ComConfig)
        ComConfig.setTabOrder(self.leConfigName, self.lePortNum)
        ComConfig.setTabOrder(self.lePortNum, self.leByteSize)
        ComConfig.setTabOrder(self.leByteSize, self.leStopBit)
        ComConfig.setTabOrder(self.leStopBit, self.leBaurdrate)
        ComConfig.setTabOrder(self.leBaurdrate, self.dbParity)
        ComConfig.setTabOrder(self.dbParity, self.butAddNew)
        ComConfig.setTabOrder(self.butAddNew, self.dbConfigName)
        ComConfig.setTabOrder(self.dbConfigName, self.butDelete)

    def retranslateUi(self, ComConfig):
        _translate = QtCore.QCoreApplication.translate
        ComConfig.setWindowTitle(_translate("ComConfig", "COM Configuration"))
        self.groupBox.setTitle(_translate("ComConfig", "Add New COM Configuration"))
        self.label_3.setText(_translate("ComConfig", "Baurdrate"))
        self.leStopBit.setText(_translate("ComConfig", "1"))
        self.label_6.setText(_translate("ComConfig", "Byte Size"))
        self.leByteSize.setText(_translate("ComConfig", "8"))
        self.label_2.setText(_translate("ComConfig", "Port Number"))
        self.dbParity.setItemText(0, _translate("ComConfig", "None"))
        self.dbParity.setItemText(1, _translate("ComConfig", "Odd"))
        self.dbParity.setItemText(2, _translate("ComConfig", "Even"))
        self.label_4.setText(_translate("ComConfig", "Parity"))
        self.label_5.setText(_translate("ComConfig", "Stop Bits"))
        self.label.setText(_translate("ComConfig", "Config Name"))
        self.butAddNew.setText(_translate("ComConfig", "Add New"))
        self.groupBox_2.setTitle(_translate("ComConfig", "Delete COM Configuration"))
        self.dbConfigName.setToolTip(_translate("ComConfig", "<html><head/><body><p>Config_Name : Port_No : Baudrate : ByteSize : Parity : Stop_Bits </p></body></html>"))
        self.label_7.setText(_translate("ComConfig", "Config Name"))
        self.butDelete.setText(_translate("ComConfig", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ComConfig = QtWidgets.QWidget()
    ui = Ui_ComConfig()
    ui.setupUi(ComConfig)
    ComConfig.show()
    sys.exit(app.exec_())

