# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ddtkh\Desktop\qc_scale\qc_scale_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainGui(object):
    def setupUi(self, MainGui):
        MainGui.setObjectName("MainGui")
        MainGui.resize(803, 635)
        self.centralwidget = QtWidgets.QWidget(MainGui)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidgetMain = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidgetMain.setToolTip("")
        self.tabWidgetMain.setObjectName("tabWidgetMain")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.ptSerialLog = QtWidgets.QPlainTextEdit(self.tab_3)
        self.ptSerialLog.setGeometry(QtCore.QRect(10, 110, 761, 391))
        self.ptSerialLog.setAcceptDrops(False)
        self.ptSerialLog.setObjectName("ptSerialLog")
        self.butClearLog = QtWidgets.QPushButton(self.tab_3)
        self.butClearLog.setGeometry(QtCore.QRect(400, 510, 361, 31))
        self.butClearLog.setObjectName("butClearLog")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 391, 91))
        self.groupBox_4.setObjectName("groupBox_4")
        self.dbComConfig = QtWidgets.QComboBox(self.groupBox_4)
        self.dbComConfig.setGeometry(QtCore.QRect(80, 20, 301, 22))
        self.dbComConfig.setObjectName("dbComConfig")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.label_3.setObjectName("label_3")
        self.butComConnect = QtWidgets.QPushButton(self.groupBox_4)
        self.butComConnect.setGeometry(QtCore.QRect(290, 50, 91, 23))
        self.butComConnect.setObjectName("butComConnect")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(410, 10, 361, 91))
        self.groupBox_5.setObjectName("groupBox_5")
        self.dtStart1_2 = QtWidgets.QDateTimeEdit(self.groupBox_5)
        self.dtStart1_2.setGeometry(QtCore.QRect(60, 20, 131, 20))
        self.dtStart1_2.setCalendarPopup(True)
        self.dtStart1_2.setObjectName("dtStart1_2")
        self.label_8 = QtWidgets.QLabel(self.groupBox_5)
        self.label_8.setGeometry(QtCore.QRect(200, 20, 16, 21))
        self.label_8.setObjectName("label_8")
        self.dtEnd1_2 = QtWidgets.QDateTimeEdit(self.groupBox_5)
        self.dtEnd1_2.setGeometry(QtCore.QRect(220, 20, 131, 20))
        self.dtEnd1_2.setCalendarPopup(True)
        self.dtEnd1_2.setObjectName("dtEnd1_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox_5)
        self.label_9.setGeometry(QtCore.QRect(10, 20, 48, 21))
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_2.setGeometry(QtCore.QRect(20, 50, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.butPrintLog = QtWidgets.QPushButton(self.tab_3)
        self.butPrintLog.setGeometry(QtCore.QRect(20, 510, 371, 31))
        self.butPrintLog.setObjectName("butPrintLog")
        self.tabWidgetMain.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tbTieuChuan = QtWidgets.QTableWidget(self.tab)
        self.tbTieuChuan.setRowCount(1)
        self.tbTieuChuan.setColumnCount(4)
        self.tbTieuChuan.setObjectName("tbTieuChuan")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbTieuChuan.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbTieuChuan.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbTieuChuan.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbTieuChuan.setHorizontalHeaderItem(3, item)
        self.verticalLayout_2.addWidget(self.tbTieuChuan)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_11.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_11.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_11.addWidget(self.label_7)
        self.horizontalLayout_6.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.dbTenHangTab1 = QtWidgets.QComboBox(self.groupBox_3)
        self.dbTenHangTab1.setObjectName("dbTenHangTab1")
        self.verticalLayout_12.addWidget(self.dbTenHangTab1)
        self.sbMinValTab1 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.sbMinValTab1.setMaximum(999.99)
        self.sbMinValTab1.setObjectName("sbMinValTab1")
        self.verticalLayout_12.addWidget(self.sbMinValTab1)
        self.sbMaxValTab1 = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.sbMaxValTab1.setMaximum(999.99)
        self.sbMaxValTab1.setObjectName("sbMaxValTab1")
        self.verticalLayout_12.addWidget(self.sbMaxValTab1)
        self.horizontalLayout_6.addLayout(self.verticalLayout_12)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.butUpdateTieuChuanRow = QtWidgets.QPushButton(self.groupBox_3)
        self.butUpdateTieuChuanRow.setObjectName("butUpdateTieuChuanRow")
        self.verticalLayout_10.addWidget(self.butUpdateTieuChuanRow)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.butLoadTnTieuChuan = QtWidgets.QPushButton(self.tab)
        self.butLoadTnTieuChuan.setObjectName("butLoadTnTieuChuan")
        self.horizontalLayout_2.addWidget(self.butLoadTnTieuChuan)
        self.butPrintDataTab1 = QtWidgets.QPushButton(self.tab)
        self.butPrintDataTab1.setObjectName("butPrintDataTab1")
        self.horizontalLayout_2.addWidget(self.butPrintDataTab1)
        self.butExportDataTab1 = QtWidgets.QPushButton(self.tab)
        self.butExportDataTab1.setObjectName("butExportDataTab1")
        self.horizontalLayout_2.addWidget(self.butExportDataTab1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidgetMain.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tbKetQua = QtWidgets.QTableWidget(self.tab_2)
        self.tbKetQua.setRowCount(1)
        self.tbKetQua.setColumnCount(0)
        self.tbKetQua.setObjectName("tbKetQua")
        self.tbKetQua.verticalHeader().setSortIndicatorShown(False)
        self.tbKetQua.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_4.addWidget(self.tbKetQua)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.dtStart2 = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dtStart2.setCalendarPopup(True)
        self.dtStart2.setObjectName("dtStart2")
        self.horizontalLayout_11.addWidget(self.dtStart2)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        self.dtEnd2 = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dtEnd2.setCalendarPopup(True)
        self.dtEnd2.setObjectName("dtEnd2")
        self.horizontalLayout_11.addWidget(self.dtEnd2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.dbTenHangTab2 = QtWidgets.QComboBox(self.groupBox)
        self.dbTenHangTab2.setObjectName("dbTenHangTab2")
        self.verticalLayout_3.addWidget(self.dbTenHangTab2)
        self.dbDkKetQua = QtWidgets.QComboBox(self.groupBox)
        self.dbDkKetQua.setObjectName("dbDkKetQua")
        self.dbDkKetQua.addItem("")
        self.dbDkKetQua.addItem("")
        self.verticalLayout_3.addWidget(self.dbDkKetQua)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.cbDkThgian = QtWidgets.QCheckBox(self.groupBox)
        self.cbDkThgian.setObjectName("cbDkThgian")
        self.verticalLayout_9.addWidget(self.cbDkThgian)
        self.cbDkTenHang = QtWidgets.QCheckBox(self.groupBox)
        self.cbDkTenHang.setObjectName("cbDkTenHang")
        self.verticalLayout_9.addWidget(self.cbDkTenHang)
        self.cbDkKetQua = QtWidgets.QCheckBox(self.groupBox)
        self.cbDkKetQua.setObjectName("cbDkKetQua")
        self.verticalLayout_9.addWidget(self.cbDkKetQua)
        self.horizontalLayout_4.addLayout(self.verticalLayout_9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.butQrKetQua = QtWidgets.QPushButton(self.groupBox)
        self.butQrKetQua.setObjectName("butQrKetQua")
        self.verticalLayout_5.addWidget(self.butQrKetQua)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.horizontalLayout_5.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dtStart1 = QtWidgets.QDateTimeEdit(self.groupBox_2)
        self.dtStart1.setCalendarPopup(True)
        self.dtStart1.setObjectName("dtStart1")
        self.horizontalLayout.addWidget(self.dtStart1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.dtEnd1 = QtWidgets.QDateTimeEdit(self.groupBox_2)
        self.dtEnd1.setCalendarPopup(True)
        self.dtEnd1.setObjectName("dtEnd1")
        self.horizontalLayout.addWidget(self.dtEnd1)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_5.addLayout(self.verticalLayout_8)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.butQrTyLe = QtWidgets.QPushButton(self.groupBox_2)
        self.butQrTyLe.setObjectName("butQrTyLe")
        self.verticalLayout_6.addWidget(self.butQrTyLe)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.butPrintDataTab2 = QtWidgets.QPushButton(self.tab_2)
        self.butPrintDataTab2.setObjectName("butPrintDataTab2")
        self.horizontalLayout_7.addWidget(self.butPrintDataTab2)
        self.butExportDataTab2 = QtWidgets.QPushButton(self.tab_2)
        self.butExportDataTab2.setObjectName("butExportDataTab2")
        self.horizontalLayout_7.addWidget(self.butExportDataTab2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.tabWidgetMain.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tabWidgetMain)
        MainGui.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainGui)
        self.statusbar.setObjectName("statusbar")
        MainGui.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 21))
        self.menubar.setObjectName("menubar")
        self.menuMain = QtWidgets.QMenu(self.menubar)
        self.menuMain.setObjectName("menuMain")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainGui.setMenuBar(self.menubar)
        self.actionkjkj = QtWidgets.QAction(MainGui)
        self.actionkjkj.setObjectName("actionkjkj")
        self.actionkhkh = QtWidgets.QAction(MainGui)
        self.actionkhkh.setObjectName("actionkhkh")
        self.actionPassMan = QtWidgets.QAction(MainGui)
        self.actionPassMan.setObjectName("actionPassMan")
        self.actionExit = QtWidgets.QAction(MainGui)
        self.actionExit.setObjectName("actionExit")
        self.actionComConfig = QtWidgets.QAction(MainGui)
        self.actionComConfig.setObjectName("actionComConfig")
        self.menuMain.addAction(self.actionPassMan)
        self.menuMain.addAction(self.actionComConfig)
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainGui)
        self.tabWidgetMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainGui)
        MainGui.setTabOrder(self.dbComConfig, self.tabWidgetMain)
        MainGui.setTabOrder(self.tabWidgetMain, self.butComConnect)
        MainGui.setTabOrder(self.butComConnect, self.dtStart1_2)
        MainGui.setTabOrder(self.dtStart1_2, self.dtEnd1_2)
        MainGui.setTabOrder(self.dtEnd1_2, self.pushButton_2)
        MainGui.setTabOrder(self.pushButton_2, self.ptSerialLog)
        MainGui.setTabOrder(self.ptSerialLog, self.butClearLog)
        MainGui.setTabOrder(self.butClearLog, self.tbTieuChuan)
        MainGui.setTabOrder(self.tbTieuChuan, self.dbTenHangTab1)
        MainGui.setTabOrder(self.dbTenHangTab1, self.sbMinValTab1)
        MainGui.setTabOrder(self.sbMinValTab1, self.sbMaxValTab1)
        MainGui.setTabOrder(self.sbMaxValTab1, self.butUpdateTieuChuanRow)
        MainGui.setTabOrder(self.butUpdateTieuChuanRow, self.butLoadTnTieuChuan)
        MainGui.setTabOrder(self.butLoadTnTieuChuan, self.butExportDataTab1)
        MainGui.setTabOrder(self.butExportDataTab1, self.tbKetQua)
        MainGui.setTabOrder(self.tbKetQua, self.dtStart1)
        MainGui.setTabOrder(self.dtStart1, self.dtEnd1)
        MainGui.setTabOrder(self.dtEnd1, self.butQrTyLe)
        MainGui.setTabOrder(self.butQrTyLe, self.dtStart2)
        MainGui.setTabOrder(self.dtStart2, self.dtEnd2)
        MainGui.setTabOrder(self.dtEnd2, self.cbDkThgian)
        MainGui.setTabOrder(self.cbDkThgian, self.dbTenHangTab2)
        MainGui.setTabOrder(self.dbTenHangTab2, self.cbDkTenHang)
        MainGui.setTabOrder(self.cbDkTenHang, self.dbDkKetQua)
        MainGui.setTabOrder(self.dbDkKetQua, self.cbDkKetQua)
        MainGui.setTabOrder(self.cbDkKetQua, self.butQrKetQua)

    def retranslateUi(self, MainGui):
        _translate = QtCore.QCoreApplication.translate
        MainGui.setWindowTitle(_translate("MainGui", "QC Scale Data Management"))
        self.butClearLog.setText(_translate("MainGui", "Clear Log Screen"))
        self.groupBox_4.setTitle(_translate("MainGui", "COM Configuration"))
        self.dbComConfig.setToolTip(_translate("MainGui", "<html><head/><body><p>Config_Name : Port_No : Baudrate : ByteSize : Parity : Stop_Bits </p></body></html>"))
        self.label_3.setText(_translate("MainGui", "COM Config"))
        self.butComConnect.setText(_translate("MainGui", "Connect"))
        self.groupBox_5.setTitle(_translate("MainGui", "Query"))
        self.dtStart1_2.setToolTip(_translate("MainGui", "<html><head/><body><p>DateTime picker for query</p></body></html>"))
        self.label_8.setText(_translate("MainGui", "TO"))
        self.dtEnd1_2.setToolTip(_translate("MainGui", "<html><head/><body><p>DateTime picker for query</p></body></html>"))
        self.label_9.setText(_translate("MainGui", "Thời Gian:"))
        self.pushButton_2.setText(_translate("MainGui", "Connect"))
        self.butPrintLog.setText(_translate("MainGui", "Print Log "))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab_3), _translate("MainGui", "Serial History"))
        item = self.tbTieuChuan.horizontalHeaderItem(0)
        item.setText(_translate("MainGui", "No"))
        item = self.tbTieuChuan.horizontalHeaderItem(1)
        item.setText(_translate("MainGui", "Tên Hàng"))
        item = self.tbTieuChuan.horizontalHeaderItem(2)
        item.setText(_translate("MainGui", "Thấp"))
        item = self.tbTieuChuan.horizontalHeaderItem(3)
        item.setText(_translate("MainGui", "Cao"))
        self.groupBox_3.setTitle(_translate("MainGui", "Query Kết Quả"))
        self.label_5.setText(_translate("MainGui", "Tên Hàng:"))
        self.label_6.setText(_translate("MainGui", "Thấp:"))
        self.label_7.setText(_translate("MainGui", "Cao:"))
        self.dbTenHangTab1.setToolTip(_translate("MainGui", "<html><head/><body><p>Item name, they are pre-defined</p></body></html>"))
        self.sbMinValTab1.setToolTip(_translate("MainGui", "<html><head/><body><p>Minimum value, it\'s real number from 0.00 to 999.99</p></body></html>"))
        self.sbMaxValTab1.setToolTip(_translate("MainGui", "<html><head/><body><p>Maximum number, it\'s real number from 0.00 to 999.99</p></body></html>"))
        self.butUpdateTieuChuanRow.setToolTip(_translate("MainGui", "<html><head/><body><p>Update value for selected item</p></body></html>"))
        self.butUpdateTieuChuanRow.setText(_translate("MainGui", "Update"))
        self.butLoadTnTieuChuan.setToolTip(_translate("MainGui", "<html><head/><body><p>Reload latest data</p></body></html>"))
        self.butLoadTnTieuChuan.setText(_translate("MainGui", "Refesh Data"))
        self.butPrintDataTab1.setToolTip(_translate("MainGui", "<html><head/><body><p>Export data to excel format</p></body></html>"))
        self.butPrintDataTab1.setText(_translate("MainGui", "Print"))
        self.butExportDataTab1.setToolTip(_translate("MainGui", "<html><head/><body><p>Export data to excel format</p></body></html>"))
        self.butExportDataTab1.setText(_translate("MainGui", "Export Data"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab), _translate("MainGui", "Tiêu Chuẩn"))
        self.groupBox.setTitle(_translate("MainGui", "Query Kết Quả"))
        self.dtStart2.setToolTip(_translate("MainGui", "<html><head/><body><p>DateTime picker for query</p></body></html>"))
        self.label_2.setText(_translate("MainGui", "TO"))
        self.dtEnd2.setToolTip(_translate("MainGui", "<html><head/><body><p>DateTime picker for query</p></body></html>"))
        self.dbTenHangTab2.setToolTip(_translate("MainGui", "<html><head/><body><p>Item name, they are pre-defined</p></body></html>"))
        self.dbDkKetQua.setToolTip(_translate("MainGui", "<html><head/><body><p>Condition of product, it\'s useed for Query</p></body></html>"))
        self.dbDkKetQua.setItemText(0, _translate("MainGui", "OK"))
        self.dbDkKetQua.setItemText(1, _translate("MainGui", "NOT OK"))
        self.cbDkThgian.setText(_translate("MainGui", "Thời Gian"))
        self.cbDkTenHang.setText(_translate("MainGui", "Tên Hàng"))
        self.cbDkKetQua.setText(_translate("MainGui", "Kết Quả"))
        self.butQrKetQua.setToolTip(_translate("MainGui", "<html><head/><body><p>Query “tblKetQua” table by time range, Ten Hang and NG or OK user set (AND of 3 conditions)</p></body></html>"))
        self.butQrKetQua.setText(_translate("MainGui", "Serach"))
        self.groupBox_2.setTitle(_translate("MainGui", "Query Tỷ Lệ"))
        self.label_4.setText(_translate("MainGui", "Thời Gian:"))
        self.dtStart1.setToolTip(_translate("MainGui", "<html><head/><body><p>DateTime picker for query</p></body></html>"))
        self.label.setText(_translate("MainGui", "TO"))
        self.dtEnd1.setToolTip(_translate("MainGui", "<html><head/><body><p>DateTime picker for query</p></body></html>"))
        self.butQrTyLe.setToolTip(_translate("MainGui", "<html><head/><body><p>Print out and excel out the summerized of queried result</p></body></html>"))
        self.butQrTyLe.setText(_translate("MainGui", "Serach"))
        self.butPrintDataTab2.setToolTip(_translate("MainGui", "<html><head/><body><p>Export current table to excl format</p></body></html>"))
        self.butPrintDataTab2.setText(_translate("MainGui", "Print"))
        self.butExportDataTab2.setToolTip(_translate("MainGui", "<html><head/><body><p>Export current table to excl format</p></body></html>"))
        self.butExportDataTab2.setText(_translate("MainGui", "Export"))
        self.tabWidgetMain.setTabText(self.tabWidgetMain.indexOf(self.tab_2), _translate("MainGui", "Kết Quả"))
        self.menuMain.setTitle(_translate("MainGui", "Menu"))
        self.menuAbout.setTitle(_translate("MainGui", "About"))
        self.actionkjkj.setText(_translate("MainGui", "kjkj"))
        self.actionkhkh.setText(_translate("MainGui", "khkh"))
        self.actionPassMan.setText(_translate("MainGui", "Password Manager"))
        self.actionExit.setText(_translate("MainGui", "Exit"))
        self.actionComConfig.setText(_translate("MainGui", "COM Configuration"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainGui = QtWidgets.QMainWindow()
    ui = Ui_MainGui()
    ui.setupUi(MainGui)
    MainGui.show()
    sys.exit(app.exec_())

